version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - m50
  labels:
  - dependencies
  ignore:
  - dependency-name: tailwindcss
    versions:
    - 2.1.2
  - dependency-name: react-hook-form
    versions:
    - 7.2.1
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.16
