version: "3.9"

services:
  gramophone:
    image: node:15-alpine
    command: "yarn start:dev"
    working_dir: /app/gramophone
    expose:
      - 3000
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - node_modules:/app/node_modules/bcrypt/lib
  record:
    image: node:15-alpine
    command: "yarn r start:dev"
    working_dir: /app
    expose:
      - 3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      NODE_ENV: development
      TAILWIND_MODE: watch
    volumes:
      - ./:/app
  db:
    ports:
      - "3306:3306"
    volumes:
      - database_dev:/var/lib/mysql

volumes:
  logs_dev:
  database_dev:
  node_modules:
