version: "3.9"

services:
  gramophone:
    image: node:15-alpine
    command: "yarn --cwd=/app/gramophone start:dev"
    expose:
      - 3000
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
  record:
    image: node:15-alpine
    command: "yarn --cwd=/app/record start:dev"
    expose:
      - 3000
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
  db:
    ports:
      - "3306:3306"
