name: Gramophone (backend) checks
on:
  pull_request:
    paths:
      - 'gramophone/**'
      - yarn.lock

jobs:
  unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules/"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-
      - name: Install Modules
        run: yarn g install
      - name: Run Tests
        run: yarn g test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules/"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-
      - name: Install Modules
        run: yarn g install
      - name: Run Lint
        run: yarn g lint:ci

  types:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules/"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-
      - name: Install Modules
        run: yarn g install
      - name: Run Type Check
        run: yarn g lint:types

  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules/"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-
      - name: Install Modules
        run: yarn g install
      - name: Run build
        run: yarn g build
